### ISSUE TITLE
Status of rapply in TLC

### ISSUE THREAD

**Issue by herbelin** [charguer/tlc#16]
While working on an experimental change of semantics of Ltac (coq/coq#17087), I realized that the current version of `rapply` in tlc basically reduce to a single call `refine` on a evar-free term, due to the indirection to [`old_refine`](https://github.com/charguer/tlc/blob/917411fe51bf865dc8be11876ffd1f14a1f58794/src/LibTactics.v#L682-L710) which fails on the presence of unresolved `_`. 

I tried to fix `rapply` (by inlining `old_refine`) and only one example seems to need a fix (`LibSet.v`, lemma `set_in_extens_eq`, where `typeclass` becomes useless), so it seems to be worth. Shall I propose a PR?

**Comment by charguer** [comment]
fixed
