### ISSUE TITLE
LibList vs Coq.Lists.List

### ISSUE THREAD

**Issue by hflsmax** [charguer/tlc#18]
Both lists library have useful lemmas but they are not interchangeable. Is there a way to make the lemma from one library to be used in the datatype of another?

For example, this goes through.
```
Lemma app_length_test : ∀ {A} (l1 l2 : list A), length (List.app l1 l2) = length l1 + length l2.
Proof.
  apply app_length.
Qed.
```

But this doesn't go through.
```
Lemma app_length_test : ∀ {A} (l1 l2 : list A), length (LibList.app l1 l2) = length l1 + length l2.
Proof.
  apply app_length.
```

**Comment by charguer** [comment]
The file LibListExec contains such lemmas relating Stdlib's List with TLC LibList.

**Comment by hflsmax** [comment]
Thanks!
